global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "localhost-node"
    static_configs:
      - targets: ["localhost:8080"]
  - job_name: "docker-node"
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]